name: Build

on:
  schedule:
  # 每周5 UTC 8:30运行
    - cron: '30 8 * * 5'
  push:
    branches: [ "main" ]

jobs:
  build-xray:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7

    - name: Quay login
      uses: docker/login-action@v4
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Build and push
      working-directory: ./xray
      run: |
        sudo apt install musl-tools -y
        rustup target add x86_64-unknown-linux-musl
        cargo build --target x86_64-unknown-linux-musl --release
        wget $(curl https://api.github.com/repos/XTLS/Xray-core/releases/latest | jq '.assets.[] | select(.name == "Xray-linux-64.zip") | .browser_download_url' -r)
        unzip Xray-linux-64.zip
        chmod +x ./xray
        docker build -t quay.io/dlysy/xray:cloud .
        docker push quay.io/dlysy/xray:cloud

  v2rayn:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7

    - name: Quay login
      uses: docker/login-action@v4
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Build and push
      working-directory: ./v2rayn
      run: |
        docker build -t quay.io/dlysy/v2rayn:sway .
        docker push quay.io/dlysy/v2rayn:sway


  build-darkhttpd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
      with:
        repository: 'emikulic/darkhttpd'

    - name: Quay login
      uses: docker/login-action@v4
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Build and push
      run: |
        docker build -t quay.io/dlysy/darkhttpd:latest .
        docker push quay.io/dlysy/darkhttpd:latest