name: Container

on:
  schedule:
  # 每周5 UTC 8:30运行
    - cron: '30 8 * * 5'
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Generat Config
      run: python3 ./main.py ${{ secrets.CLIENT_ID }}

    - name: Build Docker Image
      run: docker build -t ${{ secrets.ACR_URL }}/lysy-self/xray:xhttp .

    - name: ACR login
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.ACR_URL }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Push to ACR
      run: docker push ${{ secrets.ACR_URL }}/lysy-self/xray:xhttp